### ISSUE TITLE
pet.py: Creator method

### ISSUE THREAD

**Issue by oitkjf** [PythonHollywood/pet-bot#3]
I believe we've yet to implement the default state.json for state_file. Correct?

**Comment by oitkjf** [comment]
I'd also like to clarify the relation between the Pet module and the skeleton. I know we're still in very early stages, but I think I see some redundant methods. No big deal.

**Comment by JamesWyst** [comment]
That's correct--the 'state.json' file acts as a memory for the pet, but we haven't mocked it up yet.

Please point out which functions you think are redundant, that would help a lot.

We tried to segregate the Pet from the Twitter interface as much as possible.

**Comment by oitkjf** [comment]
Hello, diligent JamesWyst! Believe the hunger method is duplicative. Will look around later tonight and note any others. Thanks for all your work on this.

**Comment by JamesWyst** [comment]
I removed it--let me know if you see any more.

**Comment by belteshassar** [comment]
Closing this issue now since state-file is covered by #5 and the rest seems to be sorted.
